2025-07-14 10:59:20,771 - INFO - package: mysql.connector.plugins
2025-07-14 10:59:20,772 - INFO - plugin_name: mysql_native_password
2025-07-14 10:59:20,775 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 11:02:35,823 - INFO - package: mysql.connector.plugins
2025-07-14 11:02:35,824 - INFO - plugin_name: mysql_native_password
2025-07-14 11:02:35,827 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 11:02:36,033 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Failed executing the operation; b'upper_rate'
2025-07-14 11:02:38,694 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Failed executing the operation; b'upper_rate'
2025-07-14 11:03:10,773 - INFO - package: mysql.connector.plugins
2025-07-14 11:03:10,774 - INFO - plugin_name: mysql_native_password
2025-07-14 11:03:10,777 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 11:03:10,964 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Failed executing the operation; b'upper_rate'
2025-07-14 11:03:14,236 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Failed executing the operation; b'upper_rate'
2025-07-14 11:04:48,955 - INFO - package: mysql.connector.plugins
2025-07-14 11:04:48,956 - INFO - plugin_name: mysql_native_password
2025-07-14 11:04:48,961 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 11:04:49,232 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: 1054 (42S22): Unknown column 'upper_rate' in 'INSERT INTO'
2025-07-14 11:06:03,123 - INFO - package: mysql.connector.plugins
2025-07-14 11:06:03,124 - INFO - plugin_name: mysql_native_password
2025-07-14 11:06:03,127 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 13:20:32,676 - INFO - package: mysql.connector.plugins
2025-07-14 13:20:32,678 - INFO - plugin_name: mysql_native_password
2025-07-14 13:20:32,680 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 13:46:01,534 - INFO - package: mysql.connector.plugins
2025-07-14 13:46:01,534 - INFO - plugin_name: mysql_native_password
2025-07-14 13:46:01,536 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 14:06:00,499 - INFO - package: mysql.connector.plugins
2025-07-14 14:06:00,500 - INFO - plugin_name: mysql_native_password
2025-07-14 14:06:00,501 - INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLNativePasswordAuthPlugin
2025-07-14 14:09:53,004 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: 1264 (22003): Out of range value for column 'upper_rate' at row 14
2025-07-14 14:10:39,335 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: 1264 (22003): Out of range value for column 'upper_rate' at row 9
2025-07-14 14:11:58,438 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: 1264 (22003): Out of range value for column 'upper_rate' at row 9
2025-07-15 11:56:54,134 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Out of range value for column 'upper_rate' at row 14
2025-07-15 11:57:27,709 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Out of range value for column 'upper_rate' at row 9
2025-07-15 11:58:23,516 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Out of range value for column 'upper_rate' at row 9
2025-07-15 13:31:47,396 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Out of range value for column 'upper_rate' at row 14
2025-07-15 13:32:20,415 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Out of range value for column 'upper_rate' at row 9
2025-07-15 13:33:15,905 - ERROR - pykrx_upper_stocks 저장 중 오류 발생: Out of range value for column 'upper_rate' at row 9
2025-07-19 08:58:34,396 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:36,230 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:38,073 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:39,911 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:41,753 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:43,571 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:45,445 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:47,300 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:49,113 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:50,956 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:52,820 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:54,626 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:56,468 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:58:58,277 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:59:00,094 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:59:01,898 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:59:03,711 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
2025-07-19 08:59:05,530 - ERROR - pykrx_upper_stocks 테이블에 데이터 저장 중 오류 발생: Unknown column 'trade_condition' in 'INSERT INTO'
